### PR TITLE
feat: remove optionality of types

### PR DESCRIPTION
**Pull request by ffMathy**
Properties should not be optional here in my opinion. They should instead be optional by wrapping them in a `Partial<T>` inside the API client when querying.

At least for properties like "id" etc that are always there. I assume an entity can't exist inside Ftrack without an ID? Others are possibly required too.

Is there a more intelligent way of seeing which are required, or can you perhaps list all the required properties for me? Then I'll make the PR better.

- [x] I have added automatic tests where applicable
- [x] The PR title is suitable as a release note
- [x] The PR contains a description of what has been changed
- [x] The description contains manual test instructions

### CODE REVIEW

**Comment by jimmycallin** [comment]
hi!

I think we need the optionality on everything except `__entity_type__` and primary keys.

Primary key is 99% `id`, but we have some types where it's a combination of multiple properties. If you check the `primary_key` property in the schema, you'll find which ones are always included.

image
image
image
image

**Comment by ffMathy** [comment]
Thanks for the clarification. What about things like name? Is it possible to create a task without a name etc?

**Comment by jimmycallin** [comment]
> Thanks for the clarification. What about things like name? Is it possible to create a task without a name etc?

you will find the required fields in the `required` property in the schema

**Comment by ffMathy** [comment]
Thank you. There's now a new PR that supersedes this one: #35.

**Pull request closed without merging**
