### PR TITLE
feat: strong typed schemas

### PR DESCRIPTION
**Pull request by ffMathy**
Builds on top of #26 and #25 to add strong-typed schema and associations.

- [ ] I have added automatic tests where applicable
- [ ] The PR title is suitable as a release note
- [ ] The PR contains a description of what has been changed
- [ ] The description contains manual test instructions

### CODE REVIEW

**Comment by ffMathy** [comment]
I will finish this and submit for review when the PR #26 and #25 are merged. This one is the glue that will bind it all together. It'll be great!

**Comment by ffMathy** [comment]
This is done now. Hmmm, since this includes #26 and #25, perhaps it just makes sense to review this all at once? Up to you.

**Comment by gismya** [comment]
Too many things to keep track of at the same time to review them simultaneously. But you could setup this one to point to the #26 branch (But that would have to be done in your repository), if you want me to be able to review this one before #26 is merged.

**Comment by ffMathy** [comment]
Yeah sure. One at a time is okay too 🙏

**Comment by ffMathy** [comment]
@gismya this one has also been resolved conflict-wise and is ready to merge!

**Comment by ffMathy** [comment]
Oh, and as part of this, I also spotted that in a prior PR I was all of a sudden using Python naming convention for the emitted types and object types. I changed that here too for consistency.

I hope that's OK.

**Comment by gismya** [comment]
Sorry for the delay, I've gone in to start looking at it a few times, but I get stuck in that I don't quite follow what's going on. Could you add further explanations of the PR to help me along?

**Comment by ffMathy** [comment]
Yeah sure @gismya! Which parts need elaboration? The purpose, or what the code is doing? Or maybe something else?

**Comment by gismya** [comment]
What is being emitted, and the use case for it. I'm not intimately familiar with the project schemas.

**Comment by ffMathy** [comment]
Ah, fair enough. I'll do my best.

The schemas decide which types can be assigned to particular object types, and also decide which statuses are available for those types.

By providing this information at runtime and compile time, there are various things we want to achieve with this:

- Strong-typing and validation of a particular entity's custom attributes. By knowing which object types the given entity can be part of, we can also provide a union type for all the custom attributes of that particular entity.
- Strong-typing and validation of statuses. So similar to above, but for statuses instead.

Imagine how great it would be if an entity's custom attributes were strong-typed. Or maybe strong-typing `parent` more efficiently (by looking at which objects can be parents of other objects). All of this is achievable with this emitted code.

And because it's tree-shakeable, it's not a problem for the runtime bundle size if not used.

Does that help?

**Review by gismya — APPROVED** [review]
It's increasingly functionality we won't have use for internally, since they concern per instance customizations rather than system wide properties (Which is where we do our work). That makes the PRs harder to review and take a bit longer, I'm sorry about that. But it's also extra welcome since it concerns parts where we don't really know what is needed. Thank you for the contributions, and I hope both you and others have use for it.

**Comment by ffMathy** [comment]
Thank you @gismya! We also hope we can contribute back soon and show how this can be useful in practice. Looking forward to it! ❤️

**Comment by ffMathy** [comment]
By the way @gismya. One more ask. Can you make a release to NPM also? Just so we can get all these PRs out also.

**Comment by gismya** [comment]
The work was on its way to release - there were some changes with linting and time zones for the tests that needed to be fixed. I must also determine why the test suite is not running for outside contributors on their PRs, but that's a later question.

It's been released now.

**Comment by ffMathy** [comment]
Thanks @gismya!

As for the failing PR, usually that's because something needs access to secrets, and secrets are not included for PRs by default.

Thats changeable in the repo setttings. Perhaps there's other interesting settings there too?

**Comment by ffMathy** [comment]
Ah okay. But in that case, you can retry the build manually and it'll work.

I guess it makes sense from a security standpoint.

**Pull request merged**
